apiVersion: v1
kind: Service
metadata:
  name: backend-local
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: backend-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-local
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-local
  template:
    metadata:
      labels:
        app: backend-local
    spec:
      containers:
      - name: backend
        image: hashicorp/http-echo
        args:
        - "-text=Backend service"
        - "-listen=:5678"
        ports:
        - containerPort: 5678
